import pygame
SPRITE_SHEET = pygame.image.load("Sprites/SpaceInvaders.png")
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_LEFT = 0
SCREEN_RIGHT = SCREEN_WIDTH
SCREEN_TOP = 0
SCREEN_BOTTOM = SCREEN_HEIGHT
PLAYER_POS = (400, 500)
ALIEN_POS_X = 100
ALIEN_POS_Y = 250
ALIEN_COL = 11
ALIEN_ROW = 5
START_X_POSITION = 100
START_Y_POSITION = 50
HORIZONTAL_STEP = 60
VERTICAL_STEP = 40
MAXIMUM_NUMBER_OF_ALIEN_BULLETS = 3
