import pygame
SPRITE_SHEET = pygame.image.load("Sprites/SpaceInvaders.png")
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_LEFT = 0
SCREEN_RIGHT = SCREEN_WIDTH
SCREEN_TOP = 0
SCREEN_BOTTOM = SCREEN_HEIGHT
PLAYER_POS = (400, 500)
ALIEN_POS_X = 100
ALIEN_POS_Y = 250
ALIEN_COL = 11
ALIEN_ROW = 5
